SQL_CRIAR_TABELA = """
CREATE TABLE IF NOT EXISTS filial (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  cod INTEGER NOT NULL,
  nome TEXT NOT NULL,
  cidade TEXT NOT NULL
)
"""

SQL_INSERIR = """
INSERT INTO (cod, nome, cidade)
VALUES (?, ?, ?)
"""